name: Flutter Android Build with Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Cache Flutter Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # Decode Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > resumate_flutter/android/app/upload-keystore.jks

      # Set up key.properties file
      - name: Set up key.properties
        run: |
          echo "storeFile=../app/upload-keystore.jks" > resumate_flutter/android/key.properties  # Match local config
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> resumate_flutter/android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> resumate_flutter/android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> resumate_flutter/android/key.properties

      - name: Get dependencies
        run: flutter pub get
        working-directory: resumate_flutter

      - name: Run Unit and Widget Tests
        run: flutter test --coverage
        working-directory: resumate_flutter

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
    

      # Verify setup with flutter doctor
      - name: Run flutter doctor
        run: flutter doctor
        working-directory: resumate_flutter

      # Build Release APK
      - name: Build APK
        run: flutter build apk --release
        working-directory: resumate_flutter

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: resumate_flutter/build/app/outputs/flutter-apk/app-release.apk

      # Build Debug APK
      - name: Build Debug APK
        run: flutter build apk --debug
        working-directory: resumate_flutter
        

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: resumate_flutter/build/app/outputs/flutter-apk/app-debug.apk